/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoSalao;

/**
 *
 * @author Dev
 */
public class AgendarServico extends javax.swing.JFrame {

    /**
     * Creates new form AgendarServico
     */
    public AgendarServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlCliente1 = new javax.swing.JLabel();
        jtCampoCliente1 = new javax.swing.JTextField();
        jbBuscar1 = new javax.swing.JButton();
        jlServico1 = new javax.swing.JLabel();
        jcServico1 = new javax.swing.JComboBox();
        jlData1 = new javax.swing.JLabel();
        jdData1 = new com.toedter.calendar.JDateChooser();
        tempoServico = new javax.swing.JLabel();
        campoTempo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlCliente2 = new javax.swing.JLabel();
        campoValor2 = new javax.swing.JTextField();
        jlCliente3 = new javax.swing.JLabel();
        campoValor3 = new javax.swing.JTextField();
        jbBuscar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 128, 128));
        setMaximumSize(new java.awt.Dimension(416, 282));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Fechar(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 128, 128));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(416, 282));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCliente1.setBackground(new java.awt.Color(255, 128, 128));
        jlCliente1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jlCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCliente1.setText("Cliente :");
        jPanel1.add(jlCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 70, -1));

        jtCampoCliente1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtCampoCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCampoCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtCampoCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 128, 326, -1));

        jbBuscar1.setBackground(new java.awt.Color(255, 128, 128));
        jbBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        jbBuscar1.setText("Confirma");
        jPanel1.add(jbBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jlServico1.setBackground(new java.awt.Color(255, 128, 128));
        jlServico1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlServico1.setForeground(new java.awt.Color(255, 255, 255));
        jlServico1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlServico1.setText("Serviço : ");
        jPanel1.add(jlServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, 77, 22));

        jcServico1.setBackground(new java.awt.Color(255, 128, 128));
        jcServico1.setForeground(new java.awt.Color(255, 255, 255));
        jcServico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcServico1ActionPerformed(evt);
            }
        });
        jPanel1.add(jcServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 161, 182, -1));

        jlData1.setBackground(new java.awt.Color(255, 128, 128));
        jlData1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlData1.setForeground(new java.awt.Color(255, 255, 255));
        jlData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlData1.setText("Data :");
        jPanel1.add(jlData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 192, 77, -1));
        jPanel1.add(jdData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 192, 126, -1));

        tempoServico.setBackground(new java.awt.Color(255, 128, 128));
        tempoServico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tempoServico.setText("Tempo de Serviço: ");
        jPanel1.add(tempoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 93, -1, -1));
        jPanel1.add(campoTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 91, 125, -1));

        jLabel1.setBackground(new java.awt.Color(255, 128, 128));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agendamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, -1, 56));

        jlCliente2.setBackground(new java.awt.Color(255, 128, 128));
        jlCliente2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCliente2.setForeground(new java.awt.Color(255, 255, 255));
        jlCliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCliente2.setText("Cod. Func:");
        jPanel1.add(jlCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 70, -1));
        jPanel1.add(campoValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 80, 47, -1));

        jlCliente3.setBackground(new java.awt.Color(255, 128, 128));
        jlCliente3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCliente3.setForeground(new java.awt.Color(255, 255, 255));
        jlCliente3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCliente3.setText("Hora:");
        jPanel1.add(jlCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 70, -1));
        jPanel1.add(campoValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 102, 47, -1));

        jbBuscar2.setBackground(new java.awt.Color(255, 128, 128));
        jbBuscar2.setForeground(new java.awt.Color(255, 255, 255));
        jbBuscar2.setText("Voltar");
        jbBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Fechar
        // TODO add your handling code here:
        Mae.agendamento.setVisible(true);
    }//GEN-LAST:event_Fechar

    private void jtCampoCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCampoCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCampoCliente1ActionPerformed

    private void jcServico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcServico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcServico1ActionPerformed

    private void jbBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTempo;
    private javax.swing.JTextField campoValor2;
    private javax.swing.JTextField campoValor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBuscar1;
    private javax.swing.JButton jbBuscar2;
    private javax.swing.JComboBox jcServico1;
    private com.toedter.calendar.JDateChooser jdData1;
    private javax.swing.JLabel jlCliente1;
    private javax.swing.JLabel jlCliente2;
    private javax.swing.JLabel jlCliente3;
    private javax.swing.JLabel jlData1;
    private javax.swing.JLabel jlServico1;
    private javax.swing.JTextField jtCampoCliente1;
    private javax.swing.JLabel tempoServico;
    // End of variables declaration//GEN-END:variables
}
