/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoSalao;

/**
 *
 * @author Dev
 */
public class Relatorios extends javax.swing.JFrame {

    int ControleParametro, controleII;

    /**
     * Creates new form Relatorios
     */
    public Relatorios() {
        initComponents();
        jcServicosParametro.setVisible(false);
        jcClientesParametro.setVisible(false);
        jcSetorServico.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcTipoRelatorio = new javax.swing.JComboBox();
        lbPeriodoInicial = new javax.swing.JLabel();
        lbPeriodoFinal = new javax.swing.JLabel();
        btGerar = new javax.swing.JButton();
        jcServicosParametro = new javax.swing.JComboBox();
        jcClientesParametro = new javax.swing.JComboBox();
        jcSetorServico = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 128, 128));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Fechar(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 128, 128));

        jcTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 - Serviços", "2 - Clientes", "3 - Movimento" }));
        jcTipoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoRelatorioActionPerformed(evt);
            }
        });

        lbPeriodoInicial.setForeground(new java.awt.Color(255, 255, 255));
        lbPeriodoInicial.setText("Periodo:");

        lbPeriodoFinal.setForeground(new java.awt.Color(255, 255, 255));
        lbPeriodoFinal.setText("Até:");

        btGerar.setBackground(new java.awt.Color(255, 128, 128));
        btGerar.setForeground(new java.awt.Color(255, 255, 255));
        btGerar.setText("Gerar");
        btGerar.setFocusPainted(false);
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        jcServicosParametro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cadastrados", "Executados", "Agendados", "Setor" }));
        jcServicosParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcServicosParametroActionPerformed(evt);
            }
        });

        jcClientesParametro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cadastrados", "Agendados", "Setor" }));
        jcClientesParametro.setToolTipText("Selecione aqui o tipo  de relatório.");

        jcSetorServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jcTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcClientesParametro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcServicosParametro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcSetorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPeriodoInicial)
                .addGap(46, 46, 46)
                .addComponent(lbPeriodoFinal)
                .addGap(62, 62, 62)
                .addComponent(btGerar)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPeriodoInicial)
                    .addComponent(lbPeriodoFinal)
                    .addComponent(btGerar)
                    .addComponent(jcClientesParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcServicosParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcSetorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcTipoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoRelatorioActionPerformed
        ControleParametro = jcTipoRelatorio.getSelectedIndex(); // criando uma variavel para receber o indice do Combobox TIPO Relatorio
        switch (ControleParametro) { // faz um switch com o valor da variavel tipoRelatorio para exibir o outro combobox de acordo com a necessidade do cliente
            case (0): {// caso seja selecionada a primeira opção do combobox torna visivel o outro CB referente ao tipo de relatorio de Serviço
                jcServicosParametro.setVisible(true);
                jcClientesParametro.setVisible(false);
                jcSetorServico.setVisible(false);
                jdPeriodoFinalDataRelatorio.setVisible(true);
                jdPeriodoInicialRelatorio.setVisible(true);
                lbPeriodoFinal.setVisible(true);
                lbPeriodoInicial.setVisible(true);
                break;
            }
            case (1): {// caso seja selecionada a segunda opção do combobox torna visivel o outro CB referente ao tipo de relatorio de Clients
                jcServicosParametro.setVisible(false);
                jcClientesParametro.setVisible(true);
                jcSetorServico.setVisible(false);
                jdPeriodoFinalDataRelatorio.setVisible(true);
                jdPeriodoInicialRelatorio.setVisible(true);
                lbPeriodoFinal.setVisible(true);
                lbPeriodoInicial.setVisible(true);
                break;
            }
            case (2): {
                jcServicosParametro.setVisible(false);
                jcClientesParametro.setVisible(false);
                jcSetorServico.setVisible(false);
                jdPeriodoFinalDataRelatorio.setVisible(true);
                jdPeriodoInicialRelatorio.setVisible(true);
                lbPeriodoFinal.setVisible(true);
                lbPeriodoInicial.setVisible(true);

                break;
            }

        }
    }//GEN-LAST:event_jcTipoRelatorioActionPerformed

    private void Fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Fechar
        Mae.Principal.setEnabled(true);
    }//GEN-LAST:event_Fechar

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed

        controleII = jcServicosParametro.getSelectedIndex();
        if (ControleParametro == 1 && jcClientesParametro.getSelectedIndex() == 0) {
            Mae.Clientes.setVisible(true);
        }

    }//GEN-LAST:event_btGerarActionPerformed

    private void jcServicosParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcServicosParametroActionPerformed
        if (ControleParametro == 0 && jcServicosParametro.getSelectedIndex() == 3) {
            jcSetorServico.setVisible(true);
            jdPeriodoFinalDataRelatorio.setVisible(false);
            jdPeriodoInicialRelatorio.setVisible(false);
            lbPeriodoFinal.setVisible(false);
            lbPeriodoInicial.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcServicosParametroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcClientesParametro;
    private javax.swing.JComboBox jcServicosParametro;
    private javax.swing.JComboBox jcSetorServico;
    private javax.swing.JComboBox jcTipoRelatorio;
    private javax.swing.JLabel lbPeriodoFinal;
    private javax.swing.JLabel lbPeriodoInicial;
    // End of variables declaration//GEN-END:variables
}
